title: Ing. Tomáš Levý
url: "https://levyto.github.io/"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

tracking_id: #

footer: yes
footer_url: #
footer_text: 9/2021

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Foo"
   link: "/"
 - name: "Bar"
   link: "/pdfs/dummy.pdf"
 - name: "Dummy"
   link: "dummy"
