title: Tomáš Levý
url: "https://levyto.github.io/"
baseurl: ""

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

tracking_id: #

site.ins_logo: true

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Publications"
   link: "/pages/publications"
 - name: "Research"
   link: "/pages/research"
 - name: "Teaching"
   link: "/pages/teaching"
 
